#VERSION=1.10
#------------ WEPS SIMULATION RUN FILE ------------
# Note: Lines beginning with '#' are comment lines.
#       Lines beginning with '#   RFD' are comments used by the interface.
#
# --USER INFORMATION
#   RFD-UserName
Excercise 5
#   RFD-FarmId RFD-TractId RFD-FieldId RFD-runtypedisp RFD-RotationYears RFD-CycleCount
 |  |  | cycle | 1 | 6
#   RFD-Site
FIPS:US-WA-021
#
# --SITE INFORMATION
#   Signed Latitude
+46.53
#   Signed Longitude
-118.90
#   RFD-Elevation(meters)
417.0 
#   RFD-ClimateFlag|RFD-cligen.station
choice|cligen|+46.75;-118.617|45|3546|HATTON 10 E|417.0
#   RFD-WindFlag|RFD-windgen.station
choice|windgen|+46.267;-119.117|727845|US|WA|PASCO/TRI-CITIES
#
# --SIMULATION PERIOD
#   RFD-StartDate(day month year)
01 01 0001
#   RFD-EndDate(day month year)
31 12 0840
#   RFD-TimeSteps(per day)
24
# --RUN FILE FILENAMES (INPUT)
#   RFD-climate file
cli_gen.cli
#   RFD-wind file
win_gen.win
#   RFD-sub-daily file
none
# --WEPS OUTPUT OPTIONS
#   RFD-ErosionSubmodelOutput
0
#   RFD-OutputFile
# null  (hasn't been used in years, so eliminate it now)
#   RFD-ReportForm
# 0 0 0 0 0 0 (not used at all, so eliminate it now)
#   RFD-OutputPeriod
#2(not used at all, so eliminate it now)
# --SIMULATION REGION INFORMATION
#   RFD-RegionAngle(degrees clockwise from North)
0.0
#   Origin coordinates of simulation region (meters)
0.0  0.0
#    RFD-XLength(meters)  RFD-YLength(meters)
365.76  365.76
#   RFD-XGrid(integer) RFD-YGrid(integer)  Grid resolution
0 0
#   RFD-Scales(place holder line - needed for older versions of WEPS)
5.5 5.5
#
#
# === BEGIN ACCOUNTING REGION SECTION ===
#
#   RFD-AccNo Number of accounting regions (zero allowed, then put no coordinate entries here)
0
#
# === END ACCOUNTING REGION SECTION ===
#
#
# === BEGIN SUBREGION SECTION ===
#
#   RFD-SubregionNo (number of subregions)
4
#
# first subregion
#
#   RFD-SubmodelOutput
0 0 0 0 0
#   RFD-DebugOutput
0 0 0 0 0
#
#   Subregion polygon coordinates (meters)
# number of coordinates
4
# list of coordinates
0.0  183
183  183
183  366
0.0  366
#   RFD-AverageSlope(ratio m/m)
-1
#   RFD-SoilRockFragments
0.0
#   RFD-SoilFile
Anders_1_90_SIL.ifc
#   RFD-ManageFile
WA-Potatoes-WntrWheat-Beans,dry-Alfalfa,4yrs-CMZ49.man
#   RFD-WaterErosionLoss
0.0000
#
# second subregion
#
#   RFD-SubmodelOutput
0 0 0 0 0
#   RFD-DebugOutput
0 0 0 0 0
#
#   Subregion polygon coordinates (meters)
# number of coordinates
4
# list of coordinates
183  183
366  183
366  366
183  366
#   RFD-AverageSlope(ratio m/m)
-1
#   RFD-SoilRockFragments
0.0
#   RFD-SoilFile
Anders_AKC_45_ST_SIL.ifc
#   RFD-ManageFile
Alfalfa, fall seed, 3yr-Potato-WWheat, circle irr CMZ49.man
#   RFD-WaterErosionLoss
0.0000
#
# third Subregion
#
#   RFD-SubmodelOutput
0 0 0 0 0
#   RFD-DebugOutput
0 0 0 0 0
#
#   Subregion region coordinates (meters)
# number of coordinates
4
# list of coordinates
0.0  0.0
183  0.0
183  183
0.0  183
#   RFD-AverageSlope(ratio m/m)
-1
#   RFD-SoilRockFragments
0.0
#   RFD-SoilFile
Norfolk_NoA_90_LS.ifc
#   RFD-ManageFile
Wheat,winter,after fallow,conv.,CMZ50.man
#   RFD-WaterErosionLoss
0.0000
#
# fourth Subregion
#
#   RFD-SubmodelOutput
0 0 0 0 0
#   RFD-DebugOutput
0 0 0 0 0
#
#   Subregion region coordinates (meters)
# number of coordinates
4
# list of coordinates
183  0.0
366  0.0
366  183
183  183
#   RFD-AverageSlope(ratio m/m)
-1
#   RFD-SoilRockFragments
0.0
#   RFD-SoilFile
Anders_1_90_SIL.ifc
#   RFD-ManageFile
Canola, fall; Fallow_ Wheat, winter; Fallow; mulch till, Z50.man
#   RFD-WaterErosionLoss
0.0000
#
# === END SUBREGION SECTION ===
#
# === BEGIN BARRIER SECTION ===
#
#   RFD-BarrierNo (number of barriers)
1
#   Note: subregion mod allows 0 barriers.
#         If zero, then put no barrier entries here.
#
#   RFD-BarrierSeasonFlg
# 0 - time interpolation
# 1 - fixed in time until next time mark
# 2 - dynamic seasons based on climate inputs
2
# number of day of year time marks for seasons
2
# number of coordinates
2
#
#   ---BEGIN--- Dynamic Seasons Input
#
#   RFD-BarrierCliBegOnFlg  (Example 1 = GDD)
1
#   RFD-BarrierCliBegOnThresh (Example 100 GDD)
100
#   RFD-BarrierCliBegOnBase (Example 5 degrees C)
5
#   RFD-BarrierCliEndOnFlg (Example 0 Specified Days)
0
#   RFD-BarrierCliEndOnThresh (Example 14 days)
14
#   RFD-BarrierCliEndOnBase (example 0, ie. no value need for this selection, but placeholder must be in file)
0
#
#   RFD-BarrierCliBegOffFlg  (Example 0 = days below specified temperature, set in Base below)
0
#   RFD-BarrierCliBegOffThresh (Example 5 days)
5
#   RFD-BarrierCliBegOffBase (Example 2 degrees C)
2
#   RFD-BarrierCliEndOffFlg (Example 1 Cooling Degree Days)
1
#   RFD-BarrierCliEndOffThresh (Example 20 CDD)
20
#   RFD-BarrierCliEndOffBase (example 2 degrees C)
2
#
#   ---END--- Dynamic Seasons Input
#
# first day of year time mark
10
# second day of year time mark
150
#   RFD-BarrierS coordinates (meters) | height (meters) | width (meters) | porosity
# first coordinate pair and data
0 0 
# first point, first time mark, height (meters), width (meters), porosity
1.0 1.0 0.7 
# first point, second time mark height (meters), width (meters), porosity
2.0 2.0 0.5
# second coordinate pair and data
0 366
# second point, first time mark height (meters), width (meters), porosity
1.5 1.5 0.6
# second point, second time mark height (meters), width (meters), porosity
3.0 3.0 0.4
#   RFD-BarrierT  type 
Shrubs 1row Climate Leaf
#
# === END BARRIER SECTION ===
#
#---------- END OF SIMULATION RUN FILE ------------
