#VERSION=1.10
#------------ WEPS SIMULATION RUN FILE ------------
# Note: Lines beginning with '#' are comment lines.
#       Lines beginning with '#   RFD' are comments used by the interface.
#
# --USER INFORMATION
#   RFD-UserName
Excercise 5
#   RFD-FarmId RFD-TractId RFD-FieldId RFD-runtypedisp RFD-RotationYears RFD-CycleCount
 |  |  | cycle | 1 | 2
#   RFD-Site
FIPS:US-WA-021
#
# --SITE INFORMATION
#   Signed Latitude
+46.53
#   Signed Longitude
-118.90
#   RFD-Elevation(meters)
417.0 
#   RFD-ClimateFlag|RFD-cligen.station
choice|cligen|+46.75;-118.617|45|3546|HATTON 10 E|417.0
#   RFD-WindFlag|RFD-windgen.station
choice|windgen|+46.267;-119.117|727845|US|WA|PASCO/TRI-CITIES
#
# --SIMULATION PERIOD
#   RFD-StartDate(day month year)
01 01 0001
#   RFD-EndDate(day month year)
31 12 0280
#   RFD-TimeSteps(per day)
24
# --RUN FILE FILENAMES (INPUT)
#   RFD-climate file
cli_gen.cli
#   RFD-wind file
win_gen.win
#   RFD-sub-daily file
none
# --WEPS OUTPUT OPTIONS
#   RFD-ErosionSubmodelOutput
0
#   RFD-OutputFile
# null  (hasn't been used in years, so eliminate it now)
#   RFD-ReportForm
# 0 0 0 0 0 0 (not used at all, so eliminate it now)
#   RFD-OutputPeriod
#2(not used at all, so eliminate it now)
# --SIMULATION REGION INFORMATION
#   RFD-RegionAngle(degrees clockwise from North)
0.0
#   Origin coordinates of simulation region (meters)
0.0  0.0
#    RFD-XLength(meters)  RFD-YLength(meters)
365.76  365.76
#   RFD-XGrid(integer) RFD-YGrid(integer)  Grid resolution
0 0
#   RFD-Scales(place holder line - needed for older versions of WEPS)
5.5 5.5
#
#
# === BEGIN ACCOUNTING REGION SECTION ===
#
#   RFD-AccNo Number of accounting regions (zero allowed, then put no coordinate entries here)
0
#
# === END ACCOUNTING REGION SECTION ===
#
#
# === BEGIN SUBREGION SECTION ===
#
#   RFD-SubregionNo (number of subregions)
4
#
# first subregion
#
#   RFD-SubmodelOutput (hydro, soil, man, crop, decomp)
2 0 0 0 0
#   RFD-DebugOutput
0 0 0 0 0
#
#   Subregion polygon coordinates (meters)
# number of coordinates
4
# list of coordinates
0.0  183
183  183
183  366
0.0  366
#   RFD-AverageSlope(ratio m/m)
-1
#   RFD-SoilRockFragments
0.0
#   RFD-SoilFile
Anders_1_90_SIL.ifc
#   RFD-ManageFile
WA-Potatoes-WntrWheat-Beans,dry-Alfalfa,4yrs-CMZ49.man
#   RFD-WaterErosionLoss
0.0000
#
# second subregion
#
#   RFD-SubmodelOutput (hydro, soil, man, crop, decomp)
7 1 1 1 3
#   RFD-DebugOutput
0 0 0 0 0
#
#   Subregion polygon coordinates (meters)
# number of coordinates
4
# list of coordinates
183  183
366  183
366  366
183  366
#   RFD-AverageSlope(ratio m/m)
-1
#   RFD-SoilRockFragments
0.0
#   RFD-SoilFile
Anders_AKC_45_ST_SIL.ifc
#   RFD-ManageFile
Alfalfa, fall seed, 3yr-Potato-WWheat, circle irr CMZ49.man
#   RFD-WaterErosionLoss
0.0000
#
# third Subregion
#
#   RFD-SubmodelOutput (hydro, soil, man, crop, decomp)
0 0 0 0 0
#   RFD-DebugOutput
0 0 0 0 0
#
#   Subregion region coordinates (meters)
# number of coordinates
4
# list of coordinates
0.0  0.0
183  0.0
183  183
0.0  183
#   RFD-AverageSlope(ratio m/m)
-1
#   RFD-SoilRockFragments
0.0
#   RFD-SoilFile
Norfolk_NoA_90_LS.ifc
#   RFD-ManageFile
Wheat,winter,after fallow,conv.,CMZ50.man
#   RFD-WaterErosionLoss
0.0000
#
# fourth Subregion
#
#   RFD-SubmodelOutput (hydro, soil, man, crop, decomp)
0 0 0 0 0
#   RFD-DebugOutput
0 0 0 0 0
#
#   Subregion region coordinates (meters)
# number of coordinates
4
# list of coordinates
183  0.0
366  0.0
366  183
183  183
#   RFD-AverageSlope(ratio m/m)
-1
#   RFD-SoilRockFragments
0.0
#   RFD-SoilFile
Anders_1_90_SIL.ifc
#   RFD-ManageFile
Canola, fall; Fallow_ Wheat, winter; Fallow; mulch till, Z50.man
#   RFD-WaterErosionLoss
0.0000
#
# === END SUBREGION SECTION ===
#
# === BEGIN BARRIER SECTION ===
#
#   RFD-BarrierNo (number of barriers)
4
#   Note: subregion mod allows 0 barriers.
#         If zero, then put no barrier entries here.
#
#   RFD-BarrierSeasonFlg
# 0 - time interpolation
# 1 - fixed in time until next time mark
# 2 - dynamic seasons based on climate inputs
2
# number of day of year time marks for seasons
2
# number of coordinates
2
#
#   ---BEGIN--- Dynamic Seasons Input
#
#   First Transition
#
#   RFD-BarrierCliBegTranFlg  (Example 0 = consecutive days above temperature)
0
#   RFD-BarrierCliBegTranThresh (Example 10 days)
10
#   RFD-BarrierCliBegTranBase (Example 3 degrees C)
3
#   RFD-BarrierCliEndTranFlg (Example 0 Specified Days)
0
#   RFD-BarrierCliEndTranThresh (Example 14 days)
14
#   RFD-BarrierCliEndTranBase (example 0, ie. no value need for this selection, but placeholder must be in file)
0
#
#   Second Transition
#
#   RFD-BarrierCliBegTranFlg  (Example 1 = consecutive days below temperature)
1
#   RFD-BarrierCliBegTranThresh (Example 10 days)
10
#   RFD-BarrierCliBegTranBase (Example 1 degrees C)
1
#   RFD-BarrierCliEndTranFlg (Example 2 Cooling Degree Days)
2
#   RFD-BarrierCliEndTranThresh (Example 20 CDD)
20
#   RFD-BarrierCliEndTranBase (example 1 degrees C)
1
#   ---END--- Dynamic Seasons Input
#
#   RFD-TimeMark(1)
30
#   RFD-TimeDesc(1)
Shrubs 1row leafoff
#   RFD-TimeMark(2)
180
#   RFD-TimeDesc(2)
Shrubs 1row leafon
#   RFD-BarrierS coordinates (meters) | height (meters) | width (meters) | porosity
# first coordinate pair and data
0 0 
# first point, first time mark
# height (meters), width (meters), porosity
1.0 1.0 0.7 
# first point, second time mark
# height (meters), width (meters), porosity
2.0 2.0 0.5
# second coordinate pair and data
0 366
# second point, first time mark height (meters), width (meters), porosity
1.5 1.5 0.6
# second point, second time mark height (meters), width (meters), porosity
3.0 3.0 0.4
#   RFD-BarrierT  type 
Shrubs 1row Climate Leaf on/off
#
#
#   RFD-BarrierSeasonFlg
# 0 - time interpolation
# 1 - fixed in time until next time mark
# 2 - dynamic seasons based on climate inputs
2
# number of day of year time marks for seasons
2
# number of coordinates
2
#
#   ---BEGIN--- Dynamic Seasons Input
#
#   First Transition
#
#   RFD-BarrierCliBegTranFlg  (Example 2 = GDD)
2
#   RFD-BarrierCliBegTranThresh (Example 100 )
100
#   RFD-BarrierCliBegTranBase (Example 5 degrees C)
5
#   RFD-BarrierCliEndTranFlg (Example 0 Specified Days)
0
#   RFD-BarrierCliEndTranThresh (Example 14 days)
14
#   RFD-BarrierCliEndTranBase (example 0, ie. no value need for this selection, but placeholder must be in file)
0
#
#   Second Transition
#
#   RFD-BarrierCliBegTranFlg  (Example 3 = Cooling Degree Days)
3
#   RFD-BarrierCliBegTranThresh (Example 20 days)
20
#   RFD-BarrierCliBegTranBase (Example 1 degrees C)
1
#   RFD-BarrierCliEndTranFlg (Example 2 Cooling Degree Days)
2
#   RFD-BarrierCliEndTranThresh (Example 20 CDD)
20
#   RFD-BarrierCliEndTranBase (example 1 degrees C)
1
#   ---END--- Dynamic Seasons Input
#
#   RFD-TimeMark(1)
10
#   RFD-TimeDesc(1)
Shrubs 1row leafoff
#   RFD-TimeMark(2)
150
#   RFD-TimeDesc(2)
Shrubs 1row leafon
#   RFD-BarrierS coordinates (meters) | height (meters) | width (meters) | porosity
# first coordinate pair and data
0 366 
# first point, first time mark, height (meters), width (meters), porosity
1.0 1.0 0.7 
# first point, second time mark height (meters), width (meters), porosity
2.0 2.0 0.5
# second coordinate pair and data
366 366
# second point, first time mark height (meters), width (meters), porosity
1.5 1.5 0.6
# second point, second time mark height (meters), width (meters), porosity
3.0 3.0 0.4
#   RFD-BarrierT  type 
Shrubs 1row Climate Leaf on/off
#
#
#   RFD-BarrierSeasonFlg
# 0 - time interpolation
# 1 - fixed in time until next time mark
# 2 - dynamic seasons based on climate inputs
2
# number of day of year time marks for seasons
2
# number of coordinates
2
#
#   ---BEGIN--- Dynamic Seasons Input
#
#   First Transition
#
#   RFD-BarrierCliBegTranFlg  (Example 4 = rainfall depth accumulation)
4
#   RFD-BarrierCliBegTranThresh (Example 20 mm)
20
#   RFD-BarrierCliBegTranBase (Example 4 mm)
4
#   RFD-BarrierCliEndTranFlg (Example 0 Specified Days)
0
#   RFD-BarrierCliEndTranThresh (Example 14 days)
14
#   RFD-BarrierCliEndTranBase (example 0, ie. no value need for this selection, but placeholder must be in file)
0
#
#   Second Transition
#
#   RFD-BarrierCliBegTranFlg  (Example 5 = days without rainfall)
5
#   RFD-BarrierCliBegTranThresh (Example 30 days)
30
#   RFD-BarrierCliBegTranBase (Example 3 mm)
1
#   RFD-BarrierCliEndTranFlg (Example 0 Days)
2
#   RFD-BarrierCliEndTranThresh (Example 60 days)
60
#   RFD-BarrierCliEndTranBase (example placeholder)
0
#   ---END--- Dynamic Seasons Input
#
#   RFD-TimeMark(1)
10
#   RFD-TimeDesc(1)
Shrubs 1row leafoff
#   RFD-TimeMark(2)
150
#   RFD-TimeDesc(2)
Shrubs 1row leafon
#   RFD-BarrierS coordinates (meters) | height (meters) | width (meters) | porosity
# first coordinate pair and data
366 366 
# first point, first time mark, height (meters), width (meters), porosity
1.0 1.0 0.7 
# first point, second time mark height (meters), width (meters), porosity
2.0 2.0 0.5
# second coordinate pair and data
366 0
# second point, first time mark height (meters), width (meters), porosity
1.5 1.5 0.6
# second point, second time mark height (meters), width (meters), porosity
3.0 3.0 0.4
#   RFD-BarrierT  type 
Shrubs 1row Climate Leaf on/off
#
#
#   RFD-BarrierSeasonFlg
# 0 - time interpolation
# 1 - fixed in time until next time mark
# 2 - dynamic seasons based on climate inputs
2
# number of day of year time marks for seasons
2
# number of coordinates
2
#
#   ---BEGIN--- Dynamic Seasons Input
#
#   First Transition
#
#   RFD-BarrierCliBegTranFlg  (Example 7 = days below specified humidity)
7
#   RFD-BarrierCliBegTranThresh (Example 20 days)
20
#   RFD-BarrierCliBegTranBase (Example 0.6, 60%)
0.6
#   RFD-BarrierCliEndTranFlg (Example 0 Specified Days)
0
#   RFD-BarrierCliEndTranThresh (Example 20 days)
14
#   RFD-BarrierCliEndTranBase (example placeholder)
0
#
#   Second Transition
#
#   RFD-BarrierCliBegTranFlg  (Example 6 = days with high humidity)
6
#   RFD-BarrierCliBegTranThresh (Example 20 days)
20
#   RFD-BarrierCliBegTranBase (Example 0.6, 60%)
0.6
#   RFD-BarrierCliEndTranFlg (Example 0 Days)
0
#   RFD-BarrierCliEndTranThresh (Example 10 days)
10
#   RFD-BarrierCliEndTranBase (example placholder)
0
#   ---END--- Dynamic Seasons Input
#
#   RFD-TimeMark(1)
10
#   RFD-TimeDesc(1)
Shrubs 1row leafon
#   RFD-TimeMark(2)
180
#   RFD-TimeDesc(2)
Shrubs 1row leafoff
#   RFD-BarrierS coordinates (meters) | height (meters) | width (meters) | porosity
# first coordinate pair and data
366 0 
# first point, first time mark, height (meters), width (meters), porosity
2.0 2.0 0.5
# first point, second time mark height (meters), width (meters), porosity
1.0 1.0 0.7
# second coordinate pair and data
0 0
# second point, first time mark height (meters), width (meters), porosity
3.0 3.0 0.4
# second point, second time mark height (meters), width (meters), porosity
1.5 1.5 0.6
#   RFD-BarrierT  type 
Shrubs 1row Climate Leaf on/off
#
# === END BARRIER SECTION ===
#
#---------- END OF SIMULATION RUN FILE ------------
