!$Author$
!$Date$
!$Revision$
!$HeadURL$

      SUBROUTINE CONST(NR, DELTFQ, TIMEDL, INTDL)

!     CALCULATES STEP FUNCTIONS TO REPRESENT NINT 
!     DELTA T AND INTENSITY = 1.0 INTERVALS FOR CONSTANT INTENSITY
!     + + + PURPOSE + + +

!     CALLED FROM DISAG
!     AUTHOR(S): D. FLANAGAN, J. ASCOUGH
!     VERSION: THIS MODULE TAKEN FROM ASCOUGH STANDALONE IRS CODE
!     DATE CODED:  3-23-2005
!     CODED BY: D. FLANAGAN

!     + + + ARGUMENT DECLARATIONS + + +

      INTEGER NR
      REAL DELTFQ, TIMEDL(*), INTDL(*) 
    
!     + + + ARGUMENT DEFINITIONS + + +
!     DELTFQ   - REAL VALUE FOR INCREMENTAL NORMALIZED RAINFALL DEPTH
!     TIMEDL() - REAL ARRAY FOR DIMENSIONLESS ELAPSED TIME
!     INTDL()  - REAL ARRAY FOR DIMENSIONLESS RAINFALL INTENSITY

!     + + + LOCAL VARIABLES + + +
      INTEGER I
      REAL FQ

!     + + + LOCAL DEFINITIONS + + +
!     I        - INTEGER VALUE FOR LOCAL LOOP
!     FQ       - REAL VALUE FOR CUMMULATIVE NORMALIZED RAINFALL DEPTH

!     + + + END SPECIFICATIONS + + +

      FQ = 0.0
      DO I = 1, NR - 1
         FQ = FQ + DELTFQ
         TIMEDL(I+1) = FQ
         INTDL(I) = 1.0
      END DO
       
      RETURN
      END
