!$Author$
!$Date$
!$Revision$
!$HeadURL$

      real den_organic, den_quartz, den_ice

!     den_organic - density of soil organic particles (Mg/m^3)
!         Particle density of organic matter
!         1.37 in Baver, Soil Physics, 1972 p.44 (humus)
!         1.1  in Marshall and Holmes, Soil Physics, 1979, p.277 (soil organic matter)

!     den_quartz - density of soil quartz articles (Mg/m^3)

      parameter(den_organic = 1.23)
      parameter(den_quartz = 2.65)
      parameter(den_ice = .92)